spring:
  application:
    name: permission_management
  datasource:
    url: jdbc:postgresql://localhost:5432/permissions
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
